### ISSUE TITLE
Claiming Steem-Engine Tokens is failing on internal browser

### ISSUE THREAD

**Issue by jayplayco** [roelandp/hivewallet#38]
Using Iphone XS with iOS 12.

* Login to a Steem-Engine Tribe within the browser of the app.
![image](https://user-images.githubusercontent.com/2923960/62985084-a24bc500-be70-11e9-9a8b-440b88af59c8.png)
* Move to the internal wallet of the tribe and claim a token.
![image](https://user-images.githubusercontent.com/2923960/62985100-b394d180-be70-11e9-8afe-32e6e0201588.png)
* Press sign&broadcast (already logged in with Keychain and both active and posting keys are included)
![image](https://user-images.githubusercontent.com/2923960/62985113-c60f0b00-be70-11e9-97c5-0176e7624c81.png)
* Using IOS, and FACE ID, FACE ID succeed, have a violet flash screen and then get a error message.
![image](https://user-images.githubusercontent.com/2923960/62985160-f8206d00-be70-11e9-9828-df38405e6618.png)

**Comment by roelandp** [comment]
Thanks great instructions to reproduce. Will work on this now.

**Comment by roelandp** [comment]
Ah... i don't have any rewards on Tribes :P Could you check if this works on the browser based SteemKeychain for FF or Chrome? thank you!

**Comment by roelandp** [comment]
Should be fixed in upcoming release 2.3.0 - awaiting the Hardfork 24 release.
